# Generated by Django 5.1.6 on 2025-06-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionfeedback',
            name='question_number',
            field=models.CharField(max_length=10),
        ),
    ]
